import type { Piece, MusicGenre, InstrumentType } from '@/services/piece/types';

export const OFFICIAL_PIECES: Piece[] = [
  {
    id: 'official-001',
    title: '小星星',
    composer: '传统民歌',
    difficulty: 1,
    instrumentTypes: ['piano'],
    genres: ['classical'],
    durationSeconds: 60,
    musicXmlUrl: '/pieces/little-star.xml',
    tags: ['入门', '儿童', '经典'],
    isOfficial: true,
    isPremium: false,
    playCount: 10000,
    favoriteCount: 5000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-002',
    title: '欢乐颂',
    composer: '贝多芬',
    difficulty: 2,
    instrumentTypes: ['piano'],
    genres: ['classical'],
    durationSeconds: 90,
    musicXmlUrl: '/pieces/ode-to-joy.xml',
    tags: ['入门', '古典', '经典'],
    isOfficial: true,
    isPremium: false,
    playCount: 8000,
    favoriteCount: 4000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-003',
    title: '卡农',
    composer: '帕赫贝尔',
    difficulty: 3,
    instrumentTypes: ['piano'],
    genres: ['classical'],
    durationSeconds: 180,
    musicXmlUrl: '/pieces/canon.xml',
    tags: ['初级', '古典', '经典'],
    isOfficial: true,
    isPremium: false,
    playCount: 15000,
    favoriteCount: 8000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-004',
    title: '月光奏鸣曲',
    composer: '贝多芬',
    difficulty: 5,
    instrumentTypes: ['piano'],
    genres: ['classical'],
    durationSeconds: 300,
    musicXmlUrl: '/pieces/moonlight-sonata.xml',
    tags: ['中级', '古典', '经典'],
    isOfficial: true,
    isPremium: true,
    playCount: 12000,
    favoriteCount: 6000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-005',
    title: '致爱丽丝',
    composer: '贝多芬',
    difficulty: 3,
    instrumentTypes: ['piano'],
    genres: ['classical'],
    durationSeconds: 180,
    musicXmlUrl: '/pieces/fur-elise.xml',
    tags: ['初级', '古典', '经典'],
    isOfficial: true,
    isPremium: false,
    playCount: 20000,
    favoriteCount: 10000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-006',
    title: '土耳其进行曲',
    composer: '莫扎特',
    difficulty: 4,
    instrumentTypes: ['piano'],
    genres: ['classical'],
    durationSeconds: 200,
    musicXmlUrl: '/pieces/turkish-march.xml',
    tags: ['初级', '古典', '经典'],
    isOfficial: true,
    isPremium: false,
    playCount: 9000,
    favoriteCount: 4500,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-007',
    title: '梦中的婚礼',
    composer: '理查德·克莱德曼',
    difficulty: 4,
    instrumentTypes: ['piano'],
    genres: ['pop'],
    durationSeconds: 240,
    musicXmlUrl: '/pieces/mariage-d-amour.xml',
    tags: ['初级', '流行', '浪漫'],
    isOfficial: true,
    isPremium: true,
    playCount: 11000,
    favoriteCount: 5500,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-008',
    title: '天空之城',
    composer: '久石让',
    difficulty: 3,
    instrumentTypes: ['piano'],
    genres: ['pop'],
    durationSeconds: 180,
    musicXmlUrl: '/pieces/castle-in-the-sky.xml',
    tags: ['初级', '流行', '动漫'],
    isOfficial: true,
    isPremium: false,
    playCount: 18000,
    favoriteCount: 9000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-009',
    title: '小提琴协奏曲',
    composer: '巴赫',
    difficulty: 7,
    instrumentTypes: ['violin'],
    genres: ['classical'],
    durationSeconds: 600,
    musicXmlUrl: '/pieces/bach-violin-concerto.xml',
    tags: ['高级', '古典', '协奏曲'],
    isOfficial: true,
    isPremium: true,
    playCount: 3000,
    favoriteCount: 1500,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-010',
    title: '吉他入门练习曲',
    composer: '传统',
    difficulty: 1,
    instrumentTypes: ['guitar'],
    genres: ['folk'],
    durationSeconds: 60,
    musicXmlUrl: '/pieces/guitar-basics.xml',
    tags: ['入门', '民谣', '基础'],
    isOfficial: true,
    isPremium: false,
    playCount: 5000,
    favoriteCount: 2500,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-011',
    title: '爱的罗曼史',
    composer: '传统',
    difficulty: 3,
    instrumentTypes: ['guitar'],
    genres: ['folk'],
    durationSeconds: 180,
    musicXmlUrl: '/pieces/romance-de-amor.xml',
    tags: ['初级', '民谣', '浪漫'],
    isOfficial: true,
    isPremium: false,
    playCount: 7000,
    favoriteCount: 3500,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-012',
    title: 'Canon in D (吉他版)',
    composer: '帕赫贝尔',
    difficulty: 5,
    instrumentTypes: ['guitar'],
    genres: ['classical'],
    durationSeconds: 240,
    musicXmlUrl: '/pieces/canon-guitar.xml',
    tags: ['中级', '古典', '经典'],
    isOfficial: true,
    isPremium: true,
    playCount: 4000,
    favoriteCount: 2000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-013',
    title: 'River Flows in You',
    composer: '李闰珉',
    difficulty: 4,
    instrumentTypes: ['piano'],
    genres: ['pop'],
    durationSeconds: 200,
    musicXmlUrl: '/pieces/river-flows-in-you.xml',
    tags: ['初级', '流行', '浪漫'],
    isOfficial: true,
    isPremium: true,
    playCount: 25000,
    favoriteCount: 12000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-014',
    title: 'Kiss the Rain',
    composer: '李闰珉',
    difficulty: 4,
    instrumentTypes: ['piano'],
    genres: ['pop'],
    durationSeconds: 220,
    musicXmlUrl: '/pieces/kiss-the-rain.xml',
    tags: ['初级', '流行', '浪漫'],
    isOfficial: true,
    isPremium: true,
    playCount: 22000,
    favoriteCount: 11000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'official-015',
    title: '巴赫大提琴独奏曲',
    composer: '巴赫',
    difficulty: 6,
    instrumentTypes: ['cello'],
    genres: ['classical'],
    durationSeconds: 480,
    musicXmlUrl: '/pieces/bach-cello-solo.xml',
    tags: ['中级', '古典', '独奏'],
    isOfficial: true,
    isPremium: true,
    playCount: 2000,
    favoriteCount: 1000,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
];

export const DIFFICULTY_LEVELS = [
  { min: 1, max: 2, label: '入门', description: '适合零基础学习者' },
  { min: 3, max: 4, label: '初级', description: '适合有一定基础的学习者' },
  { min: 5, max: 6, label: '中级', description: '适合进阶学习者' },
  { min: 7, max: 8, label: '高级', description: '适合熟练演奏者' },
  { min: 9, max: 10, label: '专业', description: '适合专业演奏者' },
];

export const GENRE_CATEGORIES = [
  { id: 'classical', label: '古典', description: '古典音乐作品' },
  { id: 'pop', label: '流行', description: '流行音乐作品' },
  { id: 'jazz', label: '爵士', description: '爵士音乐作品' },
  { id: 'folk', label: '民谣', description: '民谣音乐作品' },
  { id: 'rock', label: '摇滚', description: '摇滚音乐作品' },
];

export const INSTRUMENT_CATEGORIES = [
  { id: 'piano', label: '钢琴', piecesCount: 10 },
  { id: 'guitar', label: '吉他', piecesCount: 3 },
  { id: 'violin', label: '小提琴', piecesCount: 1 },
  { id: 'cello', label: '大提琴', piecesCount: 1 },
];

export function getOfficialPiecesByDifficulty(min: number, max: number): Piece[] {
  return OFFICIAL_PIECES.filter(p => p.difficulty >= min && p.difficulty <= max);
}

export function getOfficialPiecesByGenre(genre: MusicGenre): Piece[] {
  return OFFICIAL_PIECES.filter(p => p.genres.includes(genre));
}

export function getOfficialPiecesByInstrument(instrument: InstrumentType): Piece[] {
  return OFFICIAL_PIECES.filter(p => p.instrumentTypes.includes(instrument));
}

export function getPremiumPieces(): Piece[] {
  return OFFICIAL_PIECES.filter(p => p.isPremium);
}

export function getFreePieces(): Piece[] {
  return OFFICIAL_PIECES.filter(p => !p.isPremium);
}

export function searchOfficialPieces(query: string): Piece[] {
  const lowerQuery = query.toLowerCase();
  return OFFICIAL_PIECES.filter(p => 
    p.title.toLowerCase().includes(lowerQuery) ||
    (p.composer && p.composer.toLowerCase().includes(lowerQuery)) ||
    p.tags.some(t => t.toLowerCase().includes(lowerQuery))
  );
}